[project]
name = "gnn-rl-aicd"
version = "0.0.0"
description = "GNNs as blue agents in RL cyber-defence environments."
authors = ["Ilya Orson Sandoval <ilya.orson@gmail.com>"]
channels = ["pytorch", "conda-forge", "pyg"]
platforms = ["osx-arm64", "win-64"]

[host-dependencies]
python = "~=3.11.8"

[tasks]
install-cyborg = "pip install --no-build-isolation --no-deps --disable-pip-version-check -e ./CybORG"
install-cyborg-debugged = "pip install --no-build-isolation --no-deps --disable-pip-version-check -e ./CAGE_2_Fixed/Debugged_CybORG/CybORG"
install-sb3 = "pip install --no-build-isolation --no-deps --disable-pip-version-check --force-reinstall stable-baselines3==2.3.2"
install-sb3-custom = "pip install --no-build-isolation --no-deps --disable-pip-version-check --force-reinstall -e ./stable-baselines3"
format = "ruff format cyberdreamcatcher"
tutorial-cyborg = "jupyter-lab CybORG/CybORG/Tutorial/"
test-cyborg = "pytest CybORG/CybORG/Tests/test_sim"
eval-cardiff = "python cardiff-cage-2/evaluation.py"
train-cardiff = "python cardiff-cage-2/train.py"
train-flat-sb3-ppo = "python -m scripts.train-sb3-cyborg"
train-flat-sb3-ppo-all-scenarios = "python -m scripts.train-sb3-cyborg --multirun scenario=Scenario2,Scenario2_+_User5,Scenario2_+_User5_User6,Scenario2_+_User6,Scenario2_-_User2,Scenario2_-_User2_User4,Scenario2_-_User4"
plot-network = "python -m scripts.plot-cyborg-layout"
train-gnn-reinforce = "python -m scripts.train-gnn-reinforce"
train-gnn-ppo = "python -m scripts.train-gnn-ppo"
plot-generalization = "python -m scripts.plot-policy-performance"

[dependencies]
captum = "~=0.7"
ipython = "~=8"
jupyterlab = "~=4"
matplotlib = "~=3.8"
networkx = "~=3.2"
numpy = "~=1.26"
pandas = ">=2.2.1,<2.3"
pip = "24.*"
prettytable = "~=3.9"
python = "~=3.11"
pytorch = "~=2.1"
pyyaml = "~=6.0"
rich = "~=13.7"
paramiko = ">=3.4.0,<3.5"
pytest = ">=8.0.2,<8.1"
docutils = ">=0.20.1,<0.21"
tqdm = ">=4.66.2,<4.67"
ruff = ">=0.3.0,<0.4"
pygame = ">=2.5.2,<2.6"
seaborn = ">=0.13.2,<0.14"
bidict = ">=0.23.1,<0.24"
hydra-core = ">=1.3.2,<1.4"
tensorboard = ">=2.16.2,<2.17"
tensordict = ">=0.1.2,<0.2"
pytorch_geometric = "==2.5.0"
fsspec = ">=2024.6.1,<2025"
plotille = ">=5.0.0,<6"

[pypi-dependencies]
gymnasium = "~=0.28.1"
